/**
 * Daily Brief Generation & Retrieval Service
 * Platform Phase 16F.5 — Trusted Backend Protocol
 *
 * Calls the trusted Supabase Edge Function `generate-daily-brief`.
 * All canonical ranking and writing to `users/{userId}/briefs/{briefId}`
 * is performed exclusively by the trusted backend.
 * Client has READ-ONLY access to briefs.
 */

import { doc, getDoc, onSnapshot } from 'firebase/firestore';
import { db } from './firebase';
import { DailyBrief } from '../types/brief';
import { mapDocToDailyBrief } from './mappers/briefMapper';

const TRUSTED_BACKEND_BASE_URL =
  import.meta.env.VITE_TRUSTED_BACKEND_URL ||
  'https://fuvquwhphuheqgfdmtbh.supabase.co/functions/v1';

export class BriefGenerationService {
  /**
   * Computes the current canonical briefId for a date and edition.
   * Format: YYYY-MM-DD-morning or YYYY-MM-DD-evening
   */
  getBriefId(date = new Date(), forcedEdition?: 'morning' | 'evening'): string {
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, '0');
    const dd = String(date.getDate()).padStart(2, '0');
    const hours = date.getHours();
    const edition = forcedEdition || (hours < 16 ? 'morning' : 'evening');
    return `${yyyy}-${mm}-${dd}-${edition}`;
  }

  /**
   * Requests the trusted backend to generate or retrieve the canonical brief.
   */
  async getOrGenerateDailyBrief(
    userId: string,
    idToken: string,
    briefId?: string,
    forceRegenerate = false
  ): Promise<DailyBrief> {
    const targetBriefId = briefId || this.getBriefId();

    if (!idToken) {
      // Offline / Unauthenticated fallback: attempt direct Firestore read
      return this.readLocalBrief(userId, targetBriefId);
    }

    try {
      const response = await fetch(`${TRUSTED_BACKEND_BASE_URL}/generate-daily-brief`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${idToken}`,
        },
        body: JSON.stringify({
          briefId: targetBriefId,
          forceRegenerate,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        if (data?.brief) {
          return mapDocToDailyBrief(data.brief.briefId || targetBriefId, data.brief);
        }
      } else {
        console.warn(`[BriefGenerationService] Backend returned HTTP ${response.status}`);
      }
    } catch (err) {
      console.warn('[BriefGenerationService] Network error calling generate-daily-brief:', err);
    }

    // Fallback: Read directly from Firestore subcollection (read-only for client)
    return this.readLocalBrief(userId, targetBriefId);
  }

  /**
   * Subscribes to live daily brief updates in Firestore.
   */
  subscribeToDailyBrief(
    userId: string,
    briefId: string,
    onData: (brief: DailyBrief | null) => void,
    onError: (err: Error) => void
  ): () => void {
    if (!userId || !briefId) {
      onData(null);
      return () => {};
    }

    const docRef = doc(db, 'users', userId, 'briefs', briefId);
    return onSnapshot(
      docRef,
      (snap) => {
        if (!snap.exists()) {
          onData(null);
          return;
        }
        onData(mapDocToDailyBrief(snap.id, snap.data()));
      },
      (err) => {
        console.warn(`[BriefGenerationService] Subscription error for ${briefId}:`, err);
        onError(err);
      }
    );
  }

  /**
   * Direct read from Firestore `users/{userId}/briefs/{briefId}`.
   */
  private async readLocalBrief(userId: string, briefId: string): Promise<DailyBrief> {
    const docRef = doc(db, 'users', userId, 'briefs', briefId);
    try {
      const snap = await getDoc(docRef);
      if (snap.exists()) {
        return mapDocToDailyBrief(snap.id, snap.data());
      }
    } catch (err) {
      console.warn(`[BriefGenerationService] Error reading local brief ${briefId}:`, err);
    }

    // Return empty placeholder if not yet generated by backend
    const parts = briefId.split('-');
    const edition = briefId.endsWith('evening') ? 'evening' : 'morning';
    const dateStr = parts.slice(0, 3).join('-');

    return {
      briefId,
      userId,
      edition,
      date: dateStr,
      createdAt: new Date().toISOString(),
      estimatedMinutes: 0,
      itemsCount: 0,
      items: [],
      isCompleted: false,
    };
  }
}

export const briefGenerationService = new BriefGenerationService();
