import { doc, getDoc, setDoc, collection, getDocs, onSnapshot } from 'firebase/firestore';
import { db } from './firebase';
import type { PlatformConceptRecord, CanonicalConcept, ConceptDifficulty } from '../types/knowledge';
import { toDomainConcept } from './mappers/knowledgeMapper';

// Seed dictionary of authoritative canonical concepts with concise, neutral, non-circular definitions
export const SEED_CANONICAL_CONCEPTS: Record<string, {
  id: string;
  name: string;
  aliases: string[];
  shortDefinition: string;
  category: string;
  difficulty: ConceptDifficulty;
  parentConceptIds?: string[];
  relatedConceptIds?: string[];
}> = {
  // --- Space & Rocketry Propulsion ---
  'con_rocket_propulsion': {
    id: 'con_rocket_propulsion',
    name: 'Rocket Propulsion',
    aliases: ['rocket propulsion', 'propulsion system', 'rocket engine', 'chemical propulsion'],
    shortDefinition: 'The mechanism of generating thrust by expelling high-velocity exhaust gases according to Newton’s third law of motion.',
    category: 'Space & Propulsion',
    difficulty: 'basic',
    relatedConceptIds: ['con_thrust', 'con_launch_vehicle'],
  },
  'con_thrust': {
    id: 'con_thrust',
    name: 'Thrust',
    aliases: ['thrust', 'rocket thrust', 'engine thrust', 'kilonewtons'],
    shortDefinition: 'The forward propulsive force generated by an engine to overcome aerodynamic drag and gravitational pull.',
    category: 'Space & Propulsion',
    difficulty: 'basic',
    parentConceptIds: ['con_rocket_propulsion'],
    relatedConceptIds: ['con_payload_capacity'],
  },
  'con_cryogenic_engine': {
    id: 'con_cryogenic_engine',
    name: 'Cryogenic Rocket Engine',
    aliases: ['cryogenic engine', 'cryogenic propulsion', 'liquid hydrogen and oxygen', 'cryo upper stage', 'cryogenic upper stages', 'cryogenic upper stage', 'cryogenic stage', 'liquid hydrogen'],
    shortDefinition: 'A rocket engine that uses liquefied gases stored at extremely low temperatures—typically liquid oxygen (-183°C) and liquid hydrogen (-253°C)—as oxidizer and fuel.',
    category: 'Space & Propulsion',
    difficulty: 'intermediate',
    parentConceptIds: ['con_rocket_propulsion'],
    relatedConceptIds: ['con_semi_cryogenic_engine', 'con_thrust'],
  },
  'con_semi_cryogenic_engine': {
    id: 'con_semi_cryogenic_engine',
    name: 'Semi-Cryogenic Rocket Engine',
    aliases: ['semi-cryogenic engine', 'semi-cryo', 'semi-cryogenic propulsion', 'kerosene and liquid oxygen', 'isrosene'],
    shortDefinition: 'A high-thrust rocket propulsion system that pairs a cryogenic oxidizer (liquid oxygen) with room-temperature refined hydrocarbon fuel (such as aviation-grade kerosene or Isrosene) for denser propellant storage and higher liftoff thrust.',
    category: 'Space & Propulsion',
    difficulty: 'advanced',
    parentConceptIds: ['con_rocket_propulsion', 'con_cryogenic_engine'],
    relatedConceptIds: ['con_thrust', 'con_launch_vehicle', 'con_payload_capacity'],
  },
  'con_launch_vehicle': {
    id: 'con_launch_vehicle',
    name: 'Launch Vehicle',
    aliases: ['launch vehicle', 'rocket', 'heavy-lift rocket', 'lvm3', 'gslv', 'pslv'],
    shortDefinition: 'A multi-stage rocket designed to transport satellites, spacecraft, or human crew from Earth’s surface into orbital trajectories or deep space.',
    category: 'Space & Propulsion',
    difficulty: 'basic',
    relatedConceptIds: ['con_payload_capacity', 'con_rocket_propulsion'],
  },
  'con_payload_capacity': {
    id: 'con_payload_capacity',
    name: 'Payload Capacity',
    aliases: ['payload capacity', 'payload to gto', 'payload to leo', 'lift capacity'],
    shortDefinition: 'The maximum mass of cargo, satellites, or instruments a launch vehicle can deliver into a specific target orbit.',
    category: 'Space & Propulsion',
    difficulty: 'intermediate',
    parentConceptIds: ['con_launch_vehicle'],
    relatedConceptIds: ['con_thrust'],
  },

  // --- Macroeconomics & Monetary Policy ---
  'con_repo_rate': {
    id: 'con_repo_rate',
    name: 'Repo Rate',
    aliases: ['repo rate', 'policy repo rate', 'repurchase rate', 'rbi policy rate'],
    shortDefinition: 'The benchmark interest rate at which a central bank lends short-term funds to commercial banks against government securities.',
    category: 'Macroeconomics',
    difficulty: 'basic',
    parentConceptIds: ['con_monetary_policy'],
    relatedConceptIds: ['con_inflation_targeting', 'con_interest_rate'],
  },
  'con_monetary_policy': {
    id: 'con_monetary_policy',
    name: 'Monetary Policy',
    aliases: ['monetary policy', 'monetary policy committee', 'mpc stance', 'central bank policy'],
    shortDefinition: 'The macroeconomic framework used by a central bank to manage money supply, credit availability, and interest rates to achieve sustainable economic growth and price stability.',
    category: 'Macroeconomics',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_repo_rate', 'con_inflation_targeting', 'con_fiscal_deficit'],
  },
  'con_inflation_targeting': {
    id: 'con_inflation_targeting',
    name: 'Inflation Targeting',
    aliases: ['inflation targeting', 'consumer price index', 'cpi inflation', 'retail inflation', 'inflation'],
    shortDefinition: 'A central banking framework where monetary policy is adjusted specifically to maintain the headline consumer inflation rate within an explicit target band (e.g., 4% ± 2%).',
    category: 'Macroeconomics',
    difficulty: 'intermediate',
    parentConceptIds: ['con_monetary_policy'],
    relatedConceptIds: ['con_repo_rate'],
  },
  'con_fiscal_deficit': {
    id: 'con_fiscal_deficit',
    name: 'Fiscal Deficit',
    aliases: ['fiscal deficit', 'government deficit', 'budget deficit', 'fiscal consolidation'],
    shortDefinition: 'The shortfall between a government’s total expenditure and its total revenue (excluding market borrowings), indicating total borrowing requirements.',
    category: 'Macroeconomics',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_monetary_policy'],
  },
  'con_interest_rate': {
    id: 'con_interest_rate',
    name: 'Interest Rate',
    aliases: ['interest rate', 'lending rate', 'borrowing cost', 'mclr'],
    shortDefinition: 'The proportion of a loan that is charged as interest to the borrower, typically expressed as an annual percentage of the loan outstanding.',
    category: 'Macroeconomics',
    difficulty: 'basic',
    relatedConceptIds: ['con_repo_rate'],
  },

  // --- Artificial Intelligence & Sovereign Computing ---
  'con_large_language_model': {
    id: 'con_large_language_model',
    name: 'Large Language Model (LLM)',
    aliases: ['large language model', 'llm', 'foundation model', 'frontier ai model', 'generative ai'],
    shortDefinition: 'A deep learning neural network trained on massive text corpora to understand, generate, and reason with human language across diverse tasks.',
    category: 'Artificial Intelligence',
    difficulty: 'basic',
    parentConceptIds: ['con_transformer_model'],
    relatedConceptIds: ['con_sovereign_ai', 'con_agentic_ai'],
  },
  'con_transformer_model': {
    id: 'con_transformer_model',
    name: 'Transformer Architecture',
    aliases: ['transformer', 'transformer architecture', 'self-attention mechanism', 'attention mechanism'],
    shortDefinition: 'A neural network architecture that processes sequential data in parallel using self-attention mechanisms to weigh the relative importance of words across an entire context window.',
    category: 'Artificial Intelligence',
    difficulty: 'advanced',
    relatedConceptIds: ['con_large_language_model'],
  },
  'con_sovereign_ai': {
    id: 'con_sovereign_ai',
    name: 'Sovereign AI Infrastructure',
    aliases: ['sovereign ai', 'sovereign computing', 'national ai stack', 'indigenous ai', 'indic llm'],
    shortDefinition: 'A nation’s independent capability to produce, train, deploy, and govern artificial intelligence infrastructure, compute hardware, foundational models, and datasets within its borders.',
    category: 'Artificial Intelligence',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_large_language_model', 'con_supercomputer'],
  },
  'con_agentic_ai': {
    id: 'con_agentic_ai',
    name: 'Agentic AI',
    aliases: ['agentic ai', 'autonomous agents', 'ai agents', 'agentforce'],
    shortDefinition: 'Autonomous software systems powered by AI models that can plan multi-step actions, use tools, and execute workflows without continuous human intervention.',
    category: 'Artificial Intelligence',
    difficulty: 'intermediate',
    parentConceptIds: ['con_large_language_model'],
  },
  'con_waterless_cooling': {
    id: 'con_waterless_cooling',
    name: 'Waterless Datacenter Cooling',
    aliases: ['waterless cooling', 'waterless datacenter', 'immersion cooling', 'air-cooled compute'],
    shortDefinition: 'High-density hardware thermal management systems that dissipate extreme compute heat loads without consuming municipal water supplies or evaporative towers.',
    category: 'Artificial Intelligence',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_sovereign_ai', 'con_supercomputer'],
  },
  'con_supercomputer': {
    id: 'con_supercomputer',
    name: 'Supercomputing Grid',
    aliases: ['supercomputer', 'supercomputing', 'param rudra', 'high performance computing', 'hpc'],
    shortDefinition: 'An interconnected cluster of high-performance computing nodes designed to execute quadrillions of calculations per second for scientific modeling and AI workloads.',
    category: 'Artificial Intelligence',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_sovereign_ai'],
  },

  // --- Semiconductors & Microelectronics ---
  'con_semiconductor_fab': {
    id: 'con_semiconductor_fab',
    name: 'Semiconductor Fabrication Facility (Fab)',
    aliases: ['semiconductor fab', 'wafer fab', 'semiconductor foundry', 'chip manufacturing', 'fab plant'],
    shortDefinition: 'A specialized industrial plant containing ultra-pure cleanrooms where integrated circuits and microchips are manufactured on silicon wafers.',
    category: 'Semiconductors',
    difficulty: 'basic',
    relatedConceptIds: ['con_cleanroom', 'con_atmp_osat'],
  },
  'con_cleanroom': {
    id: 'con_cleanroom',
    name: 'Cleanroom',
    aliases: ['cleanroom', 'iso class 1', 'cleanroom shell', 'dust-free environment'],
    shortDefinition: 'An engineered manufacturing space with strictly controlled air filtration, humidity, and temperature to prevent microscopic airborne particles from contaminating silicon wafers.',
    category: 'Semiconductors',
    difficulty: 'intermediate',
    parentConceptIds: ['con_semiconductor_fab'],
  },
  'con_atmp_osat': {
    id: 'con_atmp_osat',
    name: 'ATMP / OSAT Packaging',
    aliases: ['atmp', 'osat', 'assembly testing marking packaging', 'semiconductor packaging'],
    shortDefinition: 'The downstream semiconductor process where fabricated silicon wafers are cut into individual dies, packaged in protective casings, and tested before deployment in electronics.',
    category: 'Semiconductors',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_semiconductor_fab'],
  },

  // --- Electric Mobility & Power Systems ---
  'con_fast_charging': {
    id: 'con_fast_charging',
    name: 'EV Fast-Charging Infrastructure',
    aliases: ['fast charging', 'ev charging grid', 'dc fast charging', 'charging station'],
    shortDefinition: 'High-voltage direct-current (DC) power delivery systems capable of recharging an electric vehicle battery to 80% capacity in under 45 minutes.',
    category: 'Electric Mobility',
    difficulty: 'basic',
    relatedConceptIds: ['con_powertrain'],
  },
  'con_powertrain': {
    id: 'con_powertrain',
    name: 'Electric Powertrain',
    aliases: ['powertrain', 'electric motor', 'ev powertrain', 'magnetless motor'],
    shortDefinition: 'The assembly of electrical and mechanical components—including the electric motor, inverter, transmission, and controller—that converts stored battery energy into vehicle propulsion.',
    category: 'Electric Mobility',
    difficulty: 'intermediate',
    relatedConceptIds: ['con_fast_charging'],
  },

  // --- Enterprise & Digital Infrastructure ---
  'con_gcc': {
    id: 'con_gcc',
    name: 'Global Capability Centre (GCC)',
    aliases: ['gcc', 'global capability centre', 'global capability center', 'global capability centers', 'global capability centres', 'offshore tech centre', 'offshore engineering centres', 'offshore engineering centers', 'shared services'],
    shortDefinition: 'An offshore strategic enterprise unit owned by a multinational corporation that performs high-value research, engineering, and core product development.',
    category: 'Enterprise & Economy',
    difficulty: 'basic',
    relatedConceptIds: ['con_it_services'],
  },
  'con_upi': {
    id: 'con_upi',
    name: 'Unified Payments Interface (UPI)',
    aliases: ['upi', 'unified payments interface', 'instant payment system', 'instant real-time payment'],
    shortDefinition: 'A real-time payment system developed by NPCI that facilitates inter-bank peer-to-peer and person-to-merchant digital transactions via mobile devices.',
    category: 'Fintech',
    difficulty: 'basic',
    relatedConceptIds: ['con_repo_rate'],
  },
  'con_ipo': {
    id: 'con_ipo',
    name: 'Initial Public Offering (IPO)',
    aliases: ['ipo', 'initial public offering', 'public listing', 'stock market debut'],
    shortDefinition: 'The process by which a privately held company raises equity capital by offering shares to the public on an exchange for the first time.',
    category: 'Enterprise & Economy',
    difficulty: 'basic',
    relatedConceptIds: ['con_venture_capital'],
  },
  'con_venture_capital': {
    id: 'con_venture_capital',
    name: 'Venture Capital & Growth Equity',
    aliases: ['venture capital', 'series a', 'series b', 'growth equity', 'startup funding'],
    shortDefinition: 'Private equity financing provided by investors to early-stage and growth startups with perceived high long-term growth potential.',
    category: 'Enterprise & Economy',
    difficulty: 'basic',
    relatedConceptIds: ['con_ipo'],
  },
  'con_it_services': {
    id: 'con_it_services',
    name: 'IT Services & Digital Transformation',
    aliases: ['it services', 'digital transformation', 'enterprise it', 'software exports'],
    shortDefinition: 'The provision of custom software development, cloud migration, cybersecurity, and system integration services to global commercial enterprises.',
    category: 'Enterprise & Economy',
    difficulty: 'basic',
    relatedConceptIds: ['con_gcc'],
  },
};

export class CanonicalConceptService {
  private conceptCache: Map<string, CanonicalConcept> = new Map();

  constructor() {
    // Runtime starts with an empty cache and populates dynamically from Firestore
  }

  /**
   * Fetches all published canonical concepts from Firestore into cache.
   */
  async fetchAllConcepts(): Promise<CanonicalConcept[]> {
    try {
      const snap = await getDocs(collection(db, 'concepts'));
      const concepts: CanonicalConcept[] = [];
      snap.forEach(docSnap => {
        const concept = toDomainConcept({ ...(docSnap.data() as PlatformConceptRecord), id: docSnap.id });
        this.conceptCache.set(concept.id, concept);
        concepts.push(concept);
      });
      return concepts;
    } catch (err) {
      console.warn('[CanonicalConceptService] Failed to fetch concepts from Firestore:', err);
      return Array.from(this.conceptCache.values());
    }
  }

  /**
   * Subscribes to real-time canonical concepts in Firestore.
   */
  subscribeToConcepts(onData: (concepts: CanonicalConcept[]) => void, onError?: (err: Error) => void): () => void {
    return onSnapshot(
      collection(db, 'concepts'),
      (snap) => {
        const concepts: CanonicalConcept[] = [];
        snap.forEach(docSnap => {
          const concept = toDomainConcept({ ...(docSnap.data() as PlatformConceptRecord), id: docSnap.id });
          this.conceptCache.set(concept.id, concept);
          concepts.push(concept);
        });
        onData(concepts);
      },
      (err) => {
        console.warn('[CanonicalConceptService] Snapshot error:', err);
        if (onError) onError(err);
      }
    );
  }

  /**
   * Returns a canonical concept by ID.
   */
  async getConcept(conceptId: string): Promise<CanonicalConcept | null> {
    if (!conceptId) return null;
    if (this.conceptCache.has(conceptId)) {
      return this.conceptCache.get(conceptId)!;
    }

    try {
      const docRef = doc(db, 'concepts', conceptId);
      const snap = await getDoc(docRef);
      if (snap.exists()) {
        const concept = toDomainConcept({ ...(snap.data() as PlatformConceptRecord), id: snap.id });
        this.conceptCache.set(conceptId, concept);
        return concept;
      }
    } catch (err) {
      console.warn(`[CanonicalConceptService] Error fetching concept ${conceptId}:`, err);
    }
    return null;
  }

  /**
   * Returns all cached canonical concepts.
   */
  getAllCanonicalConcepts(): CanonicalConcept[] {
    return Array.from(this.conceptCache.values());
  }

  /**
   * Extracts recognized canonical concepts from arbitrary text.
   */
  extractCanonicalConcepts(text: string): CanonicalConcept[] {
    if (!text) return [];
    const normalizedText = ` ${text.toLowerCase()} `;
    const matched = new Map<string, CanonicalConcept>();

    for (const concept of this.conceptCache.values()) {
      for (const alias of concept.aliases) {
        const escaped = alias.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, 'i');

        if (regex.test(normalizedText)) {
          matched.set(concept.id, concept);
          break;
        }
      }
    }

    return Array.from(matched.values());
  }

  /**
   * Persists a canonical concept to Firestore.
   */
  async saveConcept(record: PlatformConceptRecord): Promise<void> {
    const docRef = doc(db, 'concepts', record.id);
    await setDoc(docRef, record, { merge: true });
    this.conceptCache.set(record.id, toDomainConcept(record));
  }
}

export const canonicalConceptService = new CanonicalConceptService();
